spring:
  application:
    name: dynamic-datasource
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0????SPI??????
          url: jdbc:mysql://127.0.0.1:3306/zg119?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: test
          password: f=avy!#6U35n
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0????SPI??????
          url: jdbc:mysql://127.0.0.1:3306/zg119?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: test
          password: f=avy!#6U35n
