spring:
  datasource:
    url: jdbc:mysql://219.145.215.184:3306/zg119?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Zg119admin@xfwlw
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  mapper-locations: mrwho.mybatisjava.mapper.**.xml

