spring:
  datasource:
    url: jdbc:mysql://192.168.1.131:3306/bladex?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: db_nacos
    password: Zhxf@nacos2023
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  mapper-locations: mrwho.mybatisjava.mapper.**.xml

